@startuml

package "Model" {
    class User {
        - int id
        - String username
        - String password
        - String token
        - int coins
        - int elo
        - int gamesPlayed
        - int gamesWon
        - int gamesLost
        - int gamesDrawn
    }

    class Card {
        - int id
        - String name
        - double damage
        - ElementTypeEnum element
        - CardTypeEnum type
        - MonsterTypeEnum mtype
    }

    class Package {
        - int id
        - String packageName
        - List<Card> cards
    }

    class Deck {
        - int id
        - int userId
        - List<Card> cards
    }

    class Battle {
            - where the BattleLogic is implemented
    }

    enum ElementTypeEnum {
        FIRE
        WATER
        NORMAL
    }

    enum CardTypeEnum {
        MONSTER
        SPELL
    }

    enum MonsterTypeEnum {
        GOBLIN
        DRAGON
        WIZARD
        ORK
        KNIGHT
        KRAKEN
        FIREELF
        NOMONSTER
    }
}

package "Controller" {
    class UserController {
        + handleRequest(Request): Response
    }

    class CardController {
        + handleRequest(Request): Response
    }

    class PackageController {
        + handleRequest(Request): Response
    }

    class BattleController {
        + handleRequest(Request): Response
    }

    class DeckController {
        + handleRequest(Request): Response
    }

    class ScoreboardController {
        + handleRequest(Request): Response
    }

    class SessionController {
        + handleRequest(Request): Response
    }

    class StatsController {
        + handleRequest(Request): Response
    }

    class TransactionsController {
        + handleRequest(Request): Response
    }
}

package "Service" {
    class UserService {
    }

    class CardService {
    }

    class PackageService {
    }

    class DeckService {
    }
}

package "Persistence" {
    class UserRepository {
    }

    class CardRepository {
    }

    class PackageRepository {
    }

    class DeckRepository {

    }
}

package "HTTP" {
    class Request {
    }
    class Response {
    }
    enum Method {
    }
}

@enduml
